[project]
name = "streamlit-gradio-exercise"
version = "2025.0.0"
requires-python = ">=3.12"
dependencies = [
  "jupyter",
  "matplotlib",
  "pandas"
]

[project.dependencies]
streamlit = [
  "streamlit"
]
gradio = [
  "gradio"
]